# Auto generated by createConstFile.tcl based on the type library
# of "Microsoft Office 15/root/office15/msoutl.olb".
#
# Copyright: 2007-2014 Paul Obermeier (obermeier@poSoft.de)
# Distributed under BSD license.

namespace eval ::Outlook {

    # Enumeration OlAccountType
    variable olEas 4
    variable olExchange 0
    variable olHttp 3
    variable olImap 1
    variable olOtherAccount 5
    variable olPop3 2

    # Enumeration OlActionCopyLike
    variable olForward 2
    variable olReply 0
    variable olReplyAll 1
    variable olReplyFolder 3
    variable olRespond 4

    # Enumeration OlActionReplyStyle
    variable olEmbedOriginalItem 1
    variable olIncludeOriginalText 2
    variable olIndentOriginalText 3
    variable olLinkOriginalItem 4
    variable olOmitOriginalText 0
    variable olReplyTickOriginalText 1000
    variable olUserPreference 5

    # Enumeration OlActionResponseStyle
    variable olOpen 0
    variable olPrompt 2
    variable olSend 1

    # Enumeration OlActionShowOn
    variable olDontShow 0
    variable olMenu 1
    variable olMenuAndToolbar 2

    # Enumeration OlAddressEntryUserType
    variable olExchangeAgentAddressEntry 3
    variable olExchangeDistributionListAddressEntry 1
    variable olExchangeOrganizationAddressEntry 4
    variable olExchangePublicFolderAddressEntry 2
    variable olExchangeRemoteUserAddressEntry 5
    variable olExchangeUserAddressEntry 0
    variable olLdapAddressEntry 20
    variable olOtherAddressEntry 40
    variable olOutlookContactAddressEntry 10
    variable olOutlookDistributionListAddressEntry 11
    variable olSmtpAddressEntry 30

    # Enumeration OlAddressListType
    variable olCustomAddressList 4
    variable olExchangeContainer 1
    variable olExchangeGlobalAddressList 0
    variable olOutlookAddressList 2
    variable olOutlookLdapAddressList 3

    # Enumeration OlAlign
    variable olAlignCenter 1
    variable olAlignLeft 0
    variable olAlignRight 2

    # Enumeration OlAlignment
    variable olAlignmentLeft 0
    variable olAlignmentRight 1

    # Enumeration OlAlwaysDeleteConversation
    variable olAlwaysDelete 1
    variable olAlwaysDeleteUnsupported 2
    variable olDoNotDelete 0

    # Enumeration OlAppointmentCopyOptions
    variable olCopyAsAccept 2
    variable olCreateAppointment 1
    variable olPromptUser 0

    # Enumeration OlAppointmentTimeField
    variable olAppointmentTimeFieldEnd 3
    variable olAppointmentTimeFieldNone 1
    variable olAppointmentTimeFieldStart 2

    # Enumeration OlAttachmentBlockLevel
    variable olAttachmentBlockLevelNone 0
    variable olAttachmentBlockLevelOpen 1

    # Enumeration OlAttachmentType
    variable olByReference 4
    variable olByValue 1
    variable olEmbeddeditem 5
    variable olOLE 6

    # Enumeration OlAutoDiscoverConnectionMode
    variable olAutoDiscoverConnectionExternal 1
    variable olAutoDiscoverConnectionInternal 2
    variable olAutoDiscoverConnectionInternalDomain 3
    variable olAutoDiscoverConnectionUnknown 0

    # Enumeration OlAutoPreview
    variable olAutoPreviewAll 0
    variable olAutoPreviewNone 2
    variable olAutoPreviewUnread 1

    # Enumeration OlBackStyle
    variable olBackStyleOpaque 1
    variable olBackStyleTransparent 0

    # Enumeration OlBodyFormat
    variable olFormatHTML 2
    variable olFormatPlain 1
    variable olFormatRichText 3
    variable olFormatUnspecified 0

    # Enumeration OlBorderStyle
    variable olBorderStyleNone 0
    variable olBorderStyleSingle 1

    # Enumeration OlBusinessCardType
    variable olBusinessCardTypeInterConnect 1
    variable olBusinessCardTypeOutlook 0

    # Enumeration OlBusyStatus
    variable olBusy 2
    variable olFree 0
    variable olOutOfOffice 3
    variable olTentative 1
    variable olWorkingElsewhere 4

    # Enumeration OlCalendarDetail
    variable olFreeBusyAndSubject 1
    variable olFreeBusyOnly 0
    variable olFullDetails 2

    # Enumeration OlCalendarMailFormat
    variable olCalendarMailFormatDailySchedule 0
    variable olCalendarMailFormatEventList 1

    # Enumeration OlCalendarViewMode
    variable olCalendarView5DayWeek 4
    variable olCalendarViewDay 0
    variable olCalendarViewMonth 2
    variable olCalendarViewMultiDay 3
    variable olCalendarViewWeek 1

    # Enumeration OlCategoryColor
    variable olCategoryColorBlack 15
    variable olCategoryColorBlue 8
    variable olCategoryColorDarkBlue 23
    variable olCategoryColorDarkGray 14
    variable olCategoryColorDarkGreen 20
    variable olCategoryColorDarkMaroon 25
    variable olCategoryColorDarkOlive 22
    variable olCategoryColorDarkOrange 17
    variable olCategoryColorDarkPeach 18
    variable olCategoryColorDarkPurple 24
    variable olCategoryColorDarkRed 16
    variable olCategoryColorDarkSteel 12
    variable olCategoryColorDarkTeal 21
    variable olCategoryColorDarkYellow 19
    variable olCategoryColorGray 13
    variable olCategoryColorGreen 5
    variable olCategoryColorMaroon 10
    variable olCategoryColorNone 0
    variable olCategoryColorOlive 7
    variable olCategoryColorOrange 2
    variable olCategoryColorPeach 3
    variable olCategoryColorPurple 9
    variable olCategoryColorRed 1
    variable olCategoryColorSteel 11
    variable olCategoryColorTeal 6
    variable olCategoryColorYellow 4

    # Enumeration OlCategoryShortcutKey
    variable olCategoryShortcutKeyCtrlF10 9
    variable olCategoryShortcutKeyCtrlF11 10
    variable olCategoryShortcutKeyCtrlF12 11
    variable olCategoryShortcutKeyCtrlF2 1
    variable olCategoryShortcutKeyCtrlF3 2
    variable olCategoryShortcutKeyCtrlF4 3
    variable olCategoryShortcutKeyCtrlF5 4
    variable olCategoryShortcutKeyCtrlF6 5
    variable olCategoryShortcutKeyCtrlF7 6
    variable olCategoryShortcutKeyCtrlF8 7
    variable olCategoryShortcutKeyCtrlF9 8
    variable olCategoryShortcutKeyNone 0

    # Enumeration OlColor
    variable olAutoColor 0
    variable olColorAqua 15
    variable olColorBlack 1
    variable olColorBlue 13
    variable olColorFuchsia 14
    variable olColorGray 8
    variable olColorGreen 3
    variable olColorLime 11
    variable olColorMaroon 2
    variable olColorNavy 5
    variable olColorOlive 4
    variable olColorPurple 6
    variable olColorRed 10
    variable olColorSilver 9
    variable olColorTeal 7
    variable olColorWhite 16
    variable olColorYellow 12

    # Enumeration OlComboBoxStyle
    variable olComboBoxStyleCombo 0
    variable olComboBoxStyleList 2

    # Enumeration OlContactPhoneNumber
    variable olContactPhoneAssistant 0
    variable olContactPhoneBusiness 1
    variable olContactPhoneBusiness2 2
    variable olContactPhoneBusinessFax 3
    variable olContactPhoneCallback 4
    variable olContactPhoneCar 5
    variable olContactPhoneCompany 6
    variable olContactPhoneHome 7
    variable olContactPhoneHome2 8
    variable olContactPhoneHomeFax 9
    variable olContactPhoneISDN 10
    variable olContactPhoneMobile 11
    variable olContactPhoneOther 12
    variable olContactPhoneOtherFax 13
    variable olContactPhonePager 14
    variable olContactPhonePrimary 15
    variable olContactPhoneRadio 16
    variable olContactPhoneTTYTTD 18
    variable olContactPhoneTelex 17

    # Enumeration OlContextMenu
    variable olAttachmentContextMenu 3
    variable olFolderContextMenu 2
    variable olItemContextMenu 0
    variable olShortcutContextMenu 5
    variable olStoreContextMenu 4
    variable olViewContextMenu 1

    # Enumeration OlDayWeekTimeScale
    variable olTimeScale10Minutes 2
    variable olTimeScale15Minutes 3
    variable olTimeScale30Minutes 4
    variable olTimeScale5Minutes 0
    variable olTimeScale60Minutes 5
    variable olTimeScale6Minutes 1

    # Enumeration OlDaysOfWeek
    variable olFriday 32
    variable olMonday 2
    variable olSaturday 64
    variable olSunday 1
    variable olThursday 16
    variable olTuesday 4
    variable olWednesday 8

    # Enumeration OlDefaultExpandCollapseSetting
    variable olAllCollapsed 1
    variable olAllExpanded 0
    variable olLastViewed 2

    # Enumeration OlDefaultFolders
    variable olFolderCalendar 9
    variable olFolderConflicts 19
    variable olFolderContacts 10
    variable olFolderDeletedItems 3
    variable olFolderDrafts 16
    variable olFolderInbox 6
    variable olFolderJournal 11
    variable olFolderJunk 23
    variable olFolderLocalFailures 21
    variable olFolderManagedEmail 29
    variable olFolderNotes 12
    variable olFolderOutbox 4
    variable olFolderRssFeeds 25
    variable olFolderSentMail 5
    variable olFolderServerFailures 22
    variable olFolderSuggestedContacts 30
    variable olFolderSyncIssues 20
    variable olFolderTasks 13
    variable olFolderToDo 28
    variable olPublicFoldersAllPublicFolders 18

    # Enumeration OlDefaultSelectNamesDisplayMode
    variable olDefaultDelegates 6
    variable olDefaultMail 1
    variable olDefaultMeeting 2
    variable olDefaultMembers 5
    variable olDefaultPickRooms 8
    variable olDefaultSharingRequest 4
    variable olDefaultSingleName 7
    variable olDefaultTask 3

    # Enumeration OlDisplayType
    variable olAgent 3
    variable olDistList 1
    variable olForum 2
    variable olOrganization 4
    variable olPrivateDistList 5
    variable olRemoteUser 6
    variable olUser 0

    # Enumeration OlDownloadState
    variable olFullItem 1
    variable olHeaderOnly 0

    # Enumeration OlDragBehavior
    variable olDragBehaviorDisabled 0
    variable olDragBehaviorEnabled 1

    # Enumeration OlEditorType
    variable olEditorHTML 2
    variable olEditorRTF 3
    variable olEditorText 1
    variable olEditorWord 4

    # Enumeration OlEnterFieldBehavior
    variable olEnterFieldBehaviorRecallSelection 1
    variable olEnterFieldBehaviorSelectAll 0

    # Enumeration OlExchangeConnectionMode
    variable olCachedConnectedDrizzle 600
    variable olCachedConnectedFull 700
    variable olCachedConnectedHeaders 500
    variable olCachedDisconnected 400
    variable olCachedOffline 200
    variable olDisconnected 300
    variable olNoExchange 0
    variable olOffline 100
    variable olOnline 800

    # Enumeration OlExchangeStoreType
    variable olAdditionalExchangeMailbox 4
    variable olExchangeMailbox 1
    variable olExchangePublicFolder 2
    variable olNotExchange 3
    variable olPrimaryExchangeMailbox 0

    # Enumeration OlFlagIcon
    variable olBlueFlagIcon 5
    variable olGreenFlagIcon 3
    variable olNoFlagIcon 0
    variable olOrangeFlagIcon 2
    variable olPurpleFlagIcon 1
    variable olRedFlagIcon 6
    variable olYellowFlagIcon 4

    # Enumeration OlFlagStatus
    variable olFlagComplete 1
    variable olFlagMarked 2
    variable olNoFlag 0

    # Enumeration OlFolderDisplayMode
    variable olFolderDisplayFolderOnly 1
    variable olFolderDisplayNoNavigation 2
    variable olFolderDisplayNormal 0

    # Enumeration OlFormRegionIcon
    variable olFormRegionIconDefault 1
    variable olFormRegionIconEncrypted 9
    variable olFormRegionIconForwarded 5
    variable olFormRegionIconPage 11
    variable olFormRegionIconRead 3
    variable olFormRegionIconRecurring 12
    variable olFormRegionIconReplied 4
    variable olFormRegionIconSigned 8
    variable olFormRegionIconSubmitted 7
    variable olFormRegionIconUnread 2
    variable olFormRegionIconUnsent 6
    variable olFormRegionIconWindow 10

    # Enumeration OlFormRegionMode
    variable olFormRegionCompose 1
    variable olFormRegionPreview 2
    variable olFormRegionRead 0

    # Enumeration OlFormRegionSize
    variable olFormRegionTypeAdjoining 1
    variable olFormRegionTypeSeparate 0

    # Enumeration OlFormRegistry
    variable olDefaultRegistry 0
    variable olFolderRegistry 3
    variable olOrganizationRegistry 4
    variable olPersonalRegistry 2

    # Enumeration OlFormatCurrency
    variable olFormatCurrencyDecimal 1
    variable olFormatCurrencyNonDecimal 2

    # Enumeration OlFormatDateTime
    variable OlFormatDateTimeLongDayDate 5
    variable olFormatDateTimeBestFit 17
    variable olFormatDateTimeLongDate 6
    variable olFormatDateTimeLongDateReversed 7
    variable olFormatDateTimeLongDayDateTime 1
    variable olFormatDateTimeLongTime 15
    variable olFormatDateTimeShortDate 8
    variable olFormatDateTimeShortDateNumOnly 9
    variable olFormatDateTimeShortDateTime 2
    variable olFormatDateTimeShortDayDate 13
    variable olFormatDateTimeShortDayDateTime 3
    variable olFormatDateTimeShortDayMonth 10
    variable olFormatDateTimeShortDayMonthDateTime 4
    variable olFormatDateTimeShortMonthYear 11
    variable olFormatDateTimeShortMonthYearNumOnly 12
    variable olFormatDateTimeShortTime 16

    # Enumeration OlFormatDuration
    variable olFormatDurationLong 2
    variable olFormatDurationLongBusiness 4
    variable olFormatDurationShort 1
    variable olFormatDurationShortBusiness 3

    # Enumeration OlFormatEnumeration
    variable olFormatEnumBitmap 1
    variable olFormatEnumText 2

    # Enumeration OlFormatInteger
    variable olFormatIntegerComputer1 2
    variable olFormatIntegerComputer2 3
    variable olFormatIntegerComputer3 4
    variable olFormatIntegerPlain 1

    # Enumeration OlFormatKeywords
    variable olFormatKeywordsText 1

    # Enumeration OlFormatNumber
    variable olFormatNumber1Decimal 3
    variable olFormatNumber2Decimal 4
    variable olFormatNumberAllDigits 1
    variable olFormatNumberComputer1 6
    variable olFormatNumberComputer2 7
    variable olFormatNumberComputer3 8
    variable olFormatNumberRaw 9
    variable olFormatNumberScientific 5
    variable olFormatNumberTruncated 2

    # Enumeration OlFormatPercent
    variable olFormatPercent1Decimal 2
    variable olFormatPercent2Decimal 3
    variable olFormatPercentAllDigits 4
    variable olFormatPercentRounded 1

    # Enumeration OlFormatSmartFrom
    variable olFormatSmartFromFromOnly 2
    variable olFormatSmartFromFromTo 1

    # Enumeration OlFormatText
    variable olFormatTextText 1

    # Enumeration OlFormatYesNo
    variable olFormatYesNoIcon 4
    variable olFormatYesNoOnOff 2
    variable olFormatYesNoTrueFalse 3
    variable olFormatYesNoYesNo 1

    # Enumeration OlGender
    variable olFemale 1
    variable olMale 2
    variable olUnspecified 0

    # Enumeration OlGridLineStyle
    variable olGridLineDashes 3
    variable olGridLineLargeDots 2
    variable olGridLineNone 0
    variable olGridLineSmallDots 1
    variable olGridLineSolid 4

    # Enumeration OlGroupType
    variable olCustomFoldersGroup 0
    variable olFavoriteFoldersGroup 4
    variable olMyFoldersGroup 1
    variable olOtherFoldersGroup 3
    variable olPeopleFoldersGroup 2
    variable olReadOnlyGroup 6
    variable olRoomsGroup 5

    # Enumeration OlHorizontalLayout
    variable olHorizontalLayoutAlignCenter 1
    variable olHorizontalLayoutAlignLeft 0
    variable olHorizontalLayoutAlignRight 2
    variable olHorizontalLayoutGrow 3

    # Enumeration OlIconViewPlacement
    variable olIconAutoArrange 2
    variable olIconDoNotArrange 0
    variable olIconLineUp 1
    variable olIconSortAndAutoArrange 3

    # Enumeration OlIconViewType
    variable olIconViewLarge 0
    variable olIconViewList 2
    variable olIconViewSmall 1

    # Enumeration OlImportance
    variable olImportanceHigh 2
    variable olImportanceLow 0
    variable olImportanceNormal 1

    # Enumeration OlInspectorClose
    variable olDiscard 1
    variable olPromptForSave 2
    variable olSave 0

    # Enumeration OlItemType
    variable olAppointmentItem 1
    variable olContactItem 2
    variable olDistributionListItem 7
    variable olJournalItem 4
    variable olMailItem 0
    variable olMobileItemMMS 12
    variable olMobileItemSMS 11
    variable olNoteItem 5
    variable olPostItem 6
    variable olTaskItem 3

    # Enumeration OlJournalRecipientType
    variable olAssociatedContact 1

    # Enumeration OlMailRecipientType
    variable olBCC 3
    variable olCC 2
    variable olOriginator 0
    variable olTo 1

    # Enumeration OlMailingAddress
    variable olBusiness 2
    variable olHome 1
    variable olNone 0
    variable olOther 3

    # Enumeration OlMarkInterval
    variable olMarkComplete 5
    variable olMarkNextWeek 3
    variable olMarkNoDate 4
    variable olMarkThisWeek 2
    variable olMarkToday 0
    variable olMarkTomorrow 1

    # Enumeration OlMatchEntry
    variable olMatchEntryComplete 1
    variable olMatchEntryFirstLetter 0
    variable olMatchEntryNone 2

    # Enumeration OlMeetingRecipientType
    variable olOptional 2
    variable olOrganizer 0
    variable olRequired 1
    variable olResource 3

    # Enumeration OlMeetingResponse
    variable olMeetingAccepted 3
    variable olMeetingDeclined 4
    variable olMeetingTentative 2

    # Enumeration OlMeetingStatus
    variable olMeeting 1
    variable olMeetingCanceled 5
    variable olMeetingReceived 3
    variable olMeetingReceivedAndCanceled 7
    variable olNonMeeting 0

    # Enumeration OlMobileFormat
    variable olMMS 1
    variable olSMS 0

    # Enumeration OlMouseButton
    variable olMouseButtonLeft 1
    variable olMouseButtonMiddle 4
    variable olMouseButtonRight 2

    # Enumeration OlMousePointer
    variable olMousePointerAppStarting 13
    variable olMousePointerArrow 1
    variable olMousePointerCross 2
    variable olMousePointerCustom 99
    variable olMousePointerDefault 0
    variable olMousePointerHelp 14
    variable olMousePointerHourGlass 11
    variable olMousePointerIBeam 3
    variable olMousePointerNoDrop 12
    variable olMousePointerSizeAll 15
    variable olMousePointerSizeNESW 6
    variable olMousePointerSizeNS 7
    variable olMousePointerSizeNWSE 8
    variable olMousePointerSizeWE 9
    variable olMousePointerUpArrow 10

    # Enumeration OlMultiLine
    variable olAlwaysMultiLine 2
    variable olAlwaysSingleLine 1
    variable olWidthMultiLine 0

    # Enumeration OlMultiSelect
    variable olMultiSelectExtended 2
    variable olMultiSelectMulti 1
    variable olMultiSelectSingle 0

    # Enumeration OlNavigationModuleType
    variable olModuleCalendar 1
    variable olModuleContacts 2
    variable olModuleFolderList 6
    variable olModuleJournal 4
    variable olModuleMail 0
    variable olModuleNotes 5
    variable olModuleShortcuts 7
    variable olModuleSolutions 8
    variable olModuleTasks 3

    # Enumeration OlNetMeetingType
    variable olExchangeConferencing 2
    variable olNetMeeting 0
    variable olNetShow 1

    # Enumeration OlNoteColor
    variable olBlue 0
    variable olGreen 1
    variable olPink 2
    variable olWhite 4
    variable olYellow 3

    # Enumeration OlObjectClass
    variable olAccount 105
    variable olAccountRuleCondition 135
    variable olAccounts 106
    variable olAction 32
    variable olActions 33
    variable olAddressEntries 21
    variable olAddressEntry 8
    variable olAddressList 7
    variable olAddressLists 20
    variable olAddressRuleCondition 170
    variable olApplication 0
    variable olAppointment 26
    variable olAssignToCategoryRuleAction 122
    variable olAttachment 5
    variable olAttachmentSelection 169
    variable olAttachments 18
    variable olAutoFormatRule 147
    variable olAutoFormatRules 148
    variable olCalendarModule 159
    variable olCalendarSharing 151
    variable olCategories 153
    variable olCategory 152
    variable olCategoryRuleCondition 130
    variable olClassBusinessCardView 168
    variable olClassCalendarView 139
    variable olClassCardView 138
    variable olClassIconView 137
    variable olClassNavigationPane 155
    variable olClassPeopleView 183
    variable olClassTableView 136
    variable olClassTimeLineView 140
    variable olClassTimeZone 174
    variable olClassTimeZones 175
    variable olColumn 154
    variable olColumnFormat 149
    variable olColumns 150
    variable olConflict 102
    variable olConflicts 103
    variable olContact 40
    variable olContactsModule 160
    variable olConversation 178
    variable olConversationHeader 182
    variable olDistributionList 69
    variable olDocument 41
    variable olException 30
    variable olExceptions 29
    variable olExchangeDistributionList 111
    variable olExchangeUser 110
    variable olExplorer 34
    variable olExplorers 60
    variable olFolder 2
    variable olFolders 15
    variable olFormDescription 37
    variable olFormNameRuleCondition 131
    variable olFormRegion 129
    variable olFromRssFeedRuleCondition 173
    variable olFromRuleCondition 132
    variable olImportanceRuleCondition 128
    variable olInspector 35
    variable olInspectors 61
    variable olItemProperties 98
    variable olItemProperty 99
    variable olItems 16
    variable olJournal 42
    variable olJournalModule 162
    variable olLink 75
    variable olLinks 76
    variable olMail 43
    variable olMailModule 158
    variable olMarkAsTaskRuleAction 124
    variable olMeetingCancellation 54
    variable olMeetingForwardNotification 181
    variable olMeetingRequest 53
    variable olMeetingResponseNegative 55
    variable olMeetingResponsePositive 56
    variable olMeetingResponseTentative 57
    variable olMobile 176
    variable olMoveOrCopyRuleAction 118
    variable olNamespace 1
    variable olNavigationFolder 167
    variable olNavigationFolders 166
    variable olNavigationGroup 165
    variable olNavigationGroups 164
    variable olNavigationModule 157
    variable olNavigationModules 156
    variable olNewItemAlertRuleAction 125
    variable olNote 44
    variable olNotesModule 163
    variable olOrderField 144
    variable olOrderFields 145
    variable olOutlookBarGroup 66
    variable olOutlookBarGroups 65
    variable olOutlookBarPane 63
    variable olOutlookBarShortcut 68
    variable olOutlookBarShortcuts 67
    variable olOutlookBarStorage 64
    variable olOutspace 180
    variable olPages 36
    variable olPanes 62
    variable olPlaySoundRuleAction 123
    variable olPost 45
    variable olPropertyAccessor 112
    variable olPropertyPageSite 70
    variable olPropertyPages 71
    variable olRecipient 4
    variable olRecipients 17
    variable olRecurrencePattern 28
    variable olReminder 101
    variable olReminders 100
    variable olRemote 47
    variable olReport 46
    variable olResults 78
    variable olRow 121
    variable olRule 115
    variable olRuleAction 117
    variable olRuleActions 116
    variable olRuleCondition 127
    variable olRuleConditions 126
    variable olRules 114
    variable olSearch 77
    variable olSelectNamesDialog 109
    variable olSelection 74
    variable olSendRuleAction 119
    variable olSenderInAddressListRuleCondition 133
    variable olSharing 104
    variable olSimpleItems 179
    variable olSolutionsModule 177
    variable olStorageItem 113
    variable olStore 107
    variable olStores 108
    variable olSyncObject 72
    variable olSyncObjects 73
    variable olTable 120
    variable olTask 48
    variable olTaskRequest 49
    variable olTaskRequestAccept 51
    variable olTaskRequestDecline 52
    variable olTaskRequestUpdate 50
    variable olTasksModule 161
    variable olTextRuleCondition 134
    variable olUserDefinedProperties 172
    variable olUserDefinedProperty 171
    variable olUserProperties 38
    variable olUserProperty 39
    variable olView 80
    variable olViewField 142
    variable olViewFields 141
    variable olViewFont 146
    variable olViews 79

    # Enumeration OlOfficeDocItemsType
    variable olExcelWorkSheetItem 8
    variable olPowerPointShowItem 10
    variable olWordDocumentItem 9

    # Enumeration OlOutlookBarViewType
    variable olLargeIcon 0
    variable olSmallIcon 1

    # Enumeration OlPageType
    variable olPageTypePlanner 0
    variable olPageTypeTracker 1

    # Enumeration OlPane
    variable olFolderList 2
    variable olNavigationPane 4
    variable olOutlookBar 1
    variable olPreview 3
    variable olToDoBar 5

    # Enumeration OlPermission
    variable olDoNotForward 1
    variable olPermissionTemplate 2
    variable olUnrestricted 0

    # Enumeration OlPermissionService
    variable olPassport 2
    variable olUnknown 0
    variable olWindows 1

    # Enumeration OlPictureAlignment
    variable olPictureAlignmentLeft 0
    variable olPictureAlignmentTop 1

    # Enumeration OlRecipientSelectors
    variable olShowNone 0
    variable olShowTo 1
    variable olShowToCc 2
    variable olShowToCcBcc 3

    # Enumeration OlRecurrenceState
    variable olApptException 3
    variable olApptMaster 1
    variable olApptNotRecurring 0
    variable olApptOccurrence 2

    # Enumeration OlRecurrenceType
    variable olRecursDaily 0
    variable olRecursMonthNth 3
    variable olRecursMonthly 2
    variable olRecursWeekly 1
    variable olRecursYearNth 6
    variable olRecursYearly 5

    # Enumeration OlReferenceType
    variable olStrong 1
    variable olWeak 0

    # Enumeration OlRemoteStatus
    variable olMarkedForCopy 3
    variable olMarkedForDelete 4
    variable olMarkedForDownload 2
    variable olRemoteStatusNone 0
    variable olUnMarked 1

    # Enumeration OlResponseStatus
    variable olResponseAccepted 3
    variable olResponseDeclined 4
    variable olResponseNone 0
    variable olResponseNotResponded 5
    variable olResponseOrganized 1
    variable olResponseTentative 2

    # Enumeration OlRuleActionType
    variable olRuleActionAssignToCategory 2
    variable olRuleActionCcMessage 27
    variable olRuleActionClearCategories 30
    variable olRuleActionCopyToFolder 5
    variable olRuleActionCustomAction 22
    variable olRuleActionDefer 28
    variable olRuleActionDelete 3
    variable olRuleActionDeletePermanently 4
    variable olRuleActionDesktopAlert 24
    variable olRuleActionFlagClear 13
    variable olRuleActionFlagColor 12
    variable olRuleActionFlagForActionInDays 11
    variable olRuleActionForward 6
    variable olRuleActionForwardAsAttachment 7
    variable olRuleActionImportance 14
    variable olRuleActionMarkAsTask 29
    variable olRuleActionMarkRead 19
    variable olRuleActionMoveToFolder 1
    variable olRuleActionNewItemAlert 23
    variable olRuleActionNotifyDelivery 26
    variable olRuleActionNotifyRead 25
    variable olRuleActionPlaySound 17
    variable olRuleActionPrint 16
    variable olRuleActionRedirect 8
    variable olRuleActionRunScript 20
    variable olRuleActionSensitivity 15
    variable olRuleActionServerReply 9
    variable olRuleActionStartApplication 18
    variable olRuleActionStop 21
    variable olRuleActionTemplate 10
    variable olRuleActionUnknown 0

    # Enumeration OlRuleConditionType
    variable olConditionAccount 3
    variable olConditionAnyCategory 29
    variable olConditionBody 13
    variable olConditionBodyOrSubject 14
    variable olConditionCategory 18
    variable olConditionCc 9
    variable olConditionDateRange 22
    variable olConditionFlaggedForAction 8
    variable olConditionFormName 23
    variable olConditionFrom 1
    variable olConditionFromAnyRssFeed 31
    variable olConditionFromRssFeed 30
    variable olConditionHasAttachment 20
    variable olConditionImportance 6
    variable olConditionLocalMachineOnly 27
    variable olConditionMeetingInviteOrUpdate 26
    variable olConditionMessageHeader 15
    variable olConditionNotTo 11
    variable olConditionOOF 19
    variable olConditionOnlyToMe 4
    variable olConditionOtherMachine 28
    variable olConditionProperty 24
    variable olConditionRecipientAddress 16
    variable olConditionSenderAddress 17
    variable olConditionSenderInAddressBook 25
    variable olConditionSensitivity 7
    variable olConditionSentTo 12
    variable olConditionSizeRange 21
    variable olConditionSubject 2
    variable olConditionTo 5
    variable olConditionToOrCc 10
    variable olConditionUnknown 0

    # Enumeration OlRuleExecuteOption
    variable olRuleExecuteAllMessages 0
    variable olRuleExecuteReadMessages 1
    variable olRuleExecuteUnreadMessages 2

    # Enumeration OlRuleType
    variable olRuleReceive 0
    variable olRuleSend 1

    # Enumeration OlSaveAsType
    variable olDoc 4
    variable olHTML 5
    variable olICal 8
    variable olMHTML 10
    variable olMSG 3
    variable olMSGUnicode 9
    variable olRTF 1
    variable olTXT 0
    variable olTemplate 2
    variable olVCal 7
    variable olVCard 6

    # Enumeration OlScrollBars
    variable olScrollBarsBoth 3
    variable olScrollBarsHorizontal 1
    variable olScrollBarsNone 0
    variable olScrollBarsVertical 2

    # Enumeration OlSearchScope
    variable olSearchScopeAllFolders 1
    variable olSearchScopeAllOutlookItems 2
    variable olSearchScopeCurrentFolder 0
    variable olSearchScopeCurrentStore 4
    variable olSearchScopeSubfolders 3

    # Enumeration OlSelectionContents
    variable olConversationHeaders 1

    # Enumeration OlSelectionLocation
    variable olAttachmentWell 4
    variable olDailyTaskList 3
    variable olToDoBarAppointmentList 2
    variable olToDoBarTaskList 1
    variable olViewList 0

    # Enumeration OlSensitivity
    variable olConfidential 3
    variable olNormal 0
    variable olPersonal 1
    variable olPrivate 2

    # Enumeration OlSharingMsgType
    variable olSharingMsgTypeInvite 2
    variable olSharingMsgTypeInviteAndRequest 3
    variable olSharingMsgTypeRequest 1
    variable olSharingMsgTypeResponseAllow 4
    variable olSharingMsgTypeResponseDeny 5
    variable olSharingMsgTypeUnknown 0

    # Enumeration OlSharingProvider
    variable olProviderExchange 1
    variable olProviderFederate 7
    variable olProviderICal 4
    variable olProviderPubCal 3
    variable olProviderRSS 6
    variable olProviderSharePoint 5
    variable olProviderUnknown 0
    variable olProviderWebCal 2

    # Enumeration OlShiftState
    variable olShiftStateAltMask 4
    variable olShiftStateCtrlMask 2
    variable olShiftStateShiftMask 1

    # Enumeration OlShowItemCount
    variable olNoItemCount 0
    variable olShowTotalItemCount 2
    variable olShowUnreadItemCount 1

    # Enumeration OlSolutionScope
    variable olHideInDefaultModules 0
    variable olShowInDefaultModules 1

    # Enumeration OlSortOrder
    variable olAscending 1
    variable olDescending 2
    variable olSortNone 0

    # Enumeration OlSpecialFolders
    variable olSpecialFolderAllTasks 0
    variable olSpecialFolderReminders 1

    # Enumeration OlStorageIdentifierType
    variable olIdentifyByEntryID 1
    variable olIdentifyByMessageClass 2
    variable olIdentifyBySubject 0

    # Enumeration OlStoreType
    variable olStoreANSI 3
    variable olStoreDefault 1
    variable olStoreUnicode 2

    # Enumeration OlSyncState
    variable olSyncStarted 1
    variable olSyncStopped 0

    # Enumeration OlTableContents
    variable olHiddenItems 1
    variable olUserItems 0

    # Enumeration OlTaskDelegationState
    variable olTaskDelegationAccepted 2
    variable olTaskDelegationDeclined 3
    variable olTaskDelegationUnknown 1
    variable olTaskNotDelegated 0

    # Enumeration OlTaskOwnership
    variable olDelegatedTask 1
    variable olNewTask 0
    variable olOwnTask 2

    # Enumeration OlTaskRecipientType
    variable olFinalStatus 3
    variable olUpdate 2

    # Enumeration OlTaskResponse
    variable olTaskAccept 2
    variable olTaskAssign 1
    variable olTaskDecline 3
    variable olTaskSimple 0

    # Enumeration OlTaskStatus
    variable olTaskComplete 2
    variable olTaskDeferred 4
    variable olTaskInProgress 1
    variable olTaskNotStarted 0
    variable olTaskWaiting 3

    # Enumeration OlTextAlign
    variable olTextAlignCenter 2
    variable olTextAlignLeft 1
    variable olTextAlignRight 3

    # Enumeration OlTimeStyle
    variable olTimeStyleShortDuration 4
    variable olTimeStyleTimeDuration 1
    variable olTimeStyleTimeOnly 0

    # Enumeration OlTimelineViewMode
    variable olTimelineViewDay 0
    variable olTimelineViewMonth 2
    variable olTimelineViewWeek 1

    # Enumeration OlTrackingStatus
    variable olTrackingDelivered 1
    variable olTrackingNone 0
    variable olTrackingNotDelivered 2
    variable olTrackingNotRead 3
    variable olTrackingRead 6
    variable olTrackingRecallFailure 4
    variable olTrackingRecallSuccess 5
    variable olTrackingReplied 7

    # Enumeration OlUserPropertyType
    variable olCombination 19
    variable olCurrency 14
    variable olDateTime 5
    variable olDuration 7
    variable olEnumeration 21
    variable olFormula 18
    variable olInteger 20
    variable olKeywords 11
    variable olNumber 3
    variable olOutlookInternal 0
    variable olPercent 12
    variable olSmartFrom 22
    variable olText 1
    variable olYesNo 6

    # Enumeration OlVerticalLayout
    variable olVerticalLayoutAlignBottom 2
    variable olVerticalLayoutAlignMiddle 1
    variable olVerticalLayoutAlignTop 0
    variable olVerticalLayoutGrow 3

    # Enumeration OlViewSaveOption
    variable olViewSaveOptionAllFoldersOfType 2
    variable olViewSaveOptionThisFolderEveryone 0
    variable olViewSaveOptionThisFolderOnlyMe 1

    # Enumeration OlViewType
    variable olBusinessCardView 5
    variable olCalendarView 2
    variable olCardView 1
    variable olDailyTaskListView 6
    variable olIconView 3
    variable olPeopleView 7
    variable olTableView 0
    variable olTimelineView 4

    # Enumeration OlWindowState
    variable olMaximized 0
    variable olMinimized 1
    variable olNormalWindow 2
}
